---
output: github_document
---

# INVALSI 2021 Workshop 1

- Repository to share workshop materials

# Slides

- Introduction
- Data preparation
- Latent Class Models example
- Structural Equation Models example

>Note: press this [link to download all slides in pdf](https://www.dropbox.com/sh/asn8sp0qf7f7rvl/AAAa_gBQuha513OQbTxsPHKMa?dl=1).

# Workshop examples

## Data preparation

- Download the files to replicate the **import and export data for modelling** [example](https://www.dropbox.com/sh/li9sndp5irp0ffa/AACcp5llXkcCWKDwcFeySt7Na?dl=1).
  + link also [here](https://www.dropbox.com/sh/li9sndp5irp0ffa/AACcp5llXkcCWKDwcFeySt7Na?dl=1).

## Latent Class Models example

- Download Mplus [example](https://www.dropbox.com/sh/r18pra0fhig85y2/AACkgpBpKWuO80waD2AeTBoUa?dl=1).
  + Two country multi-group latent class model, with sample of 1000 observations to speed up estimation time.

## Structural Equation Models example

- Download the files to replicate the commented [example](https://www.dropbox.com/sh/lggup1w5h0mp4k4/AADbDIzv-O5XgpPE2-eZfKUDa?dl=1), and the presented slides.

## Authors

Sandoval-Hernández, A., PhD, Univeristy of Bath  
Carrasco, D., PhD, Centro de Medición MIDE UC  
Miranda, D., PhD, Centro de Medición MIDE UC  
Inostroza, P., Msc(c), KU Leuven  
